# Generated by Django 3.2.6 on 2021-12-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Category_name')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Place_Name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Adding_Time')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Place_Description')),
                ('region', models.CharField(max_length=100, verbose_name='Place_region')),
                ('city', models.TextField(verbose_name='Place_city')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.category')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cardimage', models.ImageField(blank=True, null=True, upload_to='images/{{ Place.name }}/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/{{ Place.name }}/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/{{ Place.name }}/')),
                ('is_poster', models.BooleanField(default=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
    ]
