# Generated by Django 3.2.6 on 2021-12-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='cardimage',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image2',
        ),
        migrations.AddField(
            model_name='place',
            name='cardimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/{{ Place.name }}/'),
        ),
    ]
