# Generated by Django 3.2.6 on 2021-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20211222_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='placeimages/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='cardimage',
            field=models.ImageField(blank=True, null=True, upload_to='cardimages/'),
        ),
    ]
