# Generated by Django 3.2.6 on 2022-01-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20211222_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(default=models.CharField(max_length=100, verbose_name='Place_Name'), max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/placeimages/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='cardimage',
            field=models.ImageField(blank=True, null=True, upload_to='static/cardimages/'),
        ),
    ]
