# Generated by Django 3.2.6 on 2022-01-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20220112_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.CharField(max_length=100, verbose_name='comment')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Adding_Time')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
    ]
