# Generated by Django 3.2.6 on 2022-02-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('text', models.CharField(max_length=100, verbose_name='text')),
            ],
        ),
    ]
