# Generated by Django 3.2.6 on 2021-12-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qid', models.CharField(max_length=100, verbose_name='qid')),
                ('answer1', models.CharField(max_length=100, verbose_name='answer1')),
                ('answer2', models.CharField(max_length=100, verbose_name='answer2')),
                ('answer3', models.CharField(max_length=100, verbose_name='answer3')),
                ('answer4', models.CharField(max_length=100, verbose_name='answer4')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100, verbose_name='question')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.answer', verbose_name='answer')),
            ],
        ),
    ]
