# Generated by Django 3.2.6 on 2022-02-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer4',
        ),
    ]
